language: java
jdk: oraclejdk8
notifications:
  slack: si5-2018-2019-pns:Qay3sY9mRk9ItOQ4tuD8Rarr
before_install:
- openssl aes-256-cbc -K $encrypted_e412fa419cdd_key -iv $encrypted_e412fa419cdd_iv
  -in secret.json.enc -out secret.json -d
- chmod +x *.sh
- chmod +x travisScripts/*.sh
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  fi
- gcloud auth activate-service-account --key-file secret.json
services:
- docker
jobs:
  include:
  - stage: Build
    name: build
    script: "./build.sh"
  - stage: Deploy
    name: deploy
    if: branch = master
    script: "./deploy.sh"
  - stage: DockerPush
    name: docker push
    if: branch = master
    script: "./travisScripts/buildAndPush.sh"
  - stage: VmDeploy
    name: Vm deploy
    script: "./travisScripts/gcloudPush.sh"
